/** Shared source for package CSS and demo theme controls. Fonts remain app-owned. */
export const themePresets = {
  "warm": {
    "background": "#fff4e6",
    "foreground": "#402b23",
    "muted": "#715548",
    "accent": "#ad4328",
    "on-accent": "#ffffff",
    "border": "#dfc5ad",
    "font": "Georgia, serif",
    "heading-weight": "400",
    "heading-tracking": ".03em",
    "section-space": "72px",
    "gap": "28px",
    "radius": "2px",
    "image-radius": "2px",
    "image-filter": "sepia(.12) saturate(.85)"
  },
  "forest": {
    "background": "#102f28",
    "foreground": "#f2f6df",
    "muted": "#bfd0b9",
    "accent": "#d5ec9c",
    "on-accent": "#173327",
    "border": "#476258",
    "font": "Georgia, serif",
    "heading-weight": "500",
    "heading-tracking": "-.025em",
    "section-space": "88px",
    "gap": "32px",
    "radius": "999px",
    "image-radius": "80px 8px 80px 8px",
    "image-filter": "saturate(.8)"
  },
  "slate": {
    "background": "#f7f7f7",
    "foreground": "#17191c",
    "muted": "#595d64",
    "accent": "#20242b",
    "on-accent": "#ffffff",
    "border": "#ced0d3",
    "font": "Arial, Helvetica, sans-serif",
    "heading-weight": "500",
    "heading-tracking": "-.04em",
    "section-space": "64px",
    "gap": "24px",
    "radius": "0px",
    "image-radius": "0px",
    "image-filter": "grayscale(1)"
  },
  "cobalt": {
    "background": "#2448ff",
    "foreground": "#ffffff",
    "muted": "#e0e7ff",
    "accent": "#ffffff",
    "on-accent": "#1933c6",
    "border": "#8499ff",
    "font": "Arial, Helvetica, sans-serif",
    "heading-weight": "800",
    "heading-tracking": "-.055em",
    "section-space": "48px",
    "gap": "16px",
    "radius": "0px",
    "image-radius": "0px",
    "image-filter": "saturate(.8) contrast(1.08)"
  },
  "citrus": {
    "background": "#d4f542",
    "foreground": "#182019",
    "muted": "#3b4625",
    "accent": "#182019",
    "on-accent": "#e5ff73",
    "border": "#91a92a",
    "font": "Arial, Helvetica, sans-serif",
    "heading-weight": "800",
    "heading-tracking": "-.05em",
    "section-space": "40px",
    "gap": "16px",
    "radius": "999px",
    "image-radius": "24px",
    "image-filter": "saturate(.9) contrast(1.1)"
  },
  "orchid": {
    "background": "#ebdeff",
    "foreground": "#341653",
    "muted": "#614779",
    "accent": "#6638d9",
    "on-accent": "#ffffff",
    "border": "#c7afe6",
    "font": "Arial, Helvetica, sans-serif",
    "heading-weight": "700",
    "heading-tracking": "-.035em",
    "section-space": "80px",
    "gap": "32px",
    "radius": "20px",
    "image-radius": "36px",
    "image-filter": "saturate(.8)"
  }
} as const;
